name: Build NII2DCM for Windows

on:
  push:
    branches: [ "main" ]

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Check out the repo (with submodules)
        uses: actions/checkout@v2
        with:
          submodules: recursive

      # - Niente set up CMake, useremo quella già nel runner

      - name: Configure (CMake)
        run: cmake -B build -A x64 -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: cmake --build build --config Release

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: nii2dcm-exe
          path: build/Release/nii2dcm.exe