name: Build NII2DCM for Windows

on:
  push:
    branches: [ "main" ]
  # Se vuoi buildare anche su pull_request o su altri branch, aggiungi:
  # pull_request:
  #   branches: [ "main" ]

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Check out the repo (with submodules)
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Set up CMake
        uses: actions/setup-cmake@v3
        with:
          cmake-version: '3.26.4' # Puoi modificare se vuoi un'altra versione

      - name: Configure (CMake)
        run: cmake -B build -A x64 -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: cmake --build build --config Release

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: nii2dcm-exe
          path: build/Release/nii2dcm.exe

